image: node:18

pipelines:
  branches:
   feature/layout:
    - step:
        name: Install Dependencies
        caches:
          - node
        script:
          - npm install --f 
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - npm run build:prod
          - cp staticwebapp.config.json ./dist/master-data-mangment/browser/staticwebapp.config.json
        artifacts:
          - 'dist/**'
    - step: 
        name: "Deploy to Azure"
        deployment: test
        script:
          - echo "$(ls -la)"
          - echo "$(ls -la ./dist)"
          - echo "$(ls -la ./dist/browser)"
          - pipe: microsoft/azure-static-web-apps-deploy:main
            variables:
                APP_LOCATION: "$BITBUCKET_CLONE_DIR/dist/master-data-mangment/browser"
                API_TOKEN: $AZURE_DEPLOYMENT_TOKEN